config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'posts#index'

  resources :users, only: [:show, :edit]
  resources :posts  do
    resources :comments, only: [:create]
  end

  #タグの検索結果表示
  resources :post_tags do
    get 'posts', to: 'posts#search'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy

  has_many :post_tag_maps, dependent: :destroy
  has_many :post_tags, through: :post_tag_maps, dependent: :destroy

  # 新規投稿の際は単純に新しいタグが保存れ、編集の際は古いタグが除外され新しいタグが保存される。
  def save_tag(sent_tags)
    #そのPostに紐付いているタグが存在する場合、「タグ名の配列として」全て取得
    current_tags = self.post_tags.pluck(:post_tag_name) unless self.post_tags.nil?
    #現在存在するタグから、送信されてきたタグを除いたタグをold_tagsとする。
    old_tags = current_tags - sent_tags
    #送信されてきたタグから、現在存在するタグを除いたタグをnew_tagsとする。
    new_tags = sent_tags - current_tags

    #old_tags内のタグを削除する
    old_tags.each do |old|
      self.post_tags.delete PostTag.find_by(post_tag_name: old)
    end

    #送信されてきたタグのみを、posts_tagsテーブルに新たに保存する
    new_tags.each do |new|
      new_post_tag = PostTag.find_or_create_by(post_tag_name: new)
      self.post_tags << new_post_tag
    end
  end
end

app/models/post_tag.rb
class PostTag < ApplicationRecord
  has_many :post_tag_maps, dependent: :destroy, foreign_key: 'post_tag_id'
  has_many :posts, through: :post_tag_maps

  # validates :post_tag_name, uniqueness: true
end

app/models/post_tag_map.rb
class PostTagMap < ApplicationRecord
  belongs_to :post
  belongs_to :post_tag

  validates :post_id, presence: true
  validates :post_tag_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @comment = current_user.comments.new(comment_params)
    if @comment.save
      redirect_back(fallback_location: root_path)
    else
      redirect_back(fallback_location: root_path)
    end
  end

  private
  def comment_params
    params.require(:comment).permit(:content, :post_id)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  # before_action :authenticate_user!, only: [:show, :create]

  def index
    @tag_list = PostTag.all

    if params[:post_tag_id]
      @tag = PostTag.find(params[:post_tag_id])
      @posts = @tag.posts.all
    else
      @posts = current_user.posts.all
      @post = current_user.posts.new
    end
  end

  def search
    @tag_list = PostTag.all
    @tag = PostTag.find(params[:post_tag_id])
    @posts = @tag.posts.all
  end

  def show
    @post = Post.find(params[:id])
    @comments = @post.comments
    @comment = current_user.comments.new
    @post_tags = @post.post_tags
  end


  def create
      @post = current_user.posts.new(post_params)
      @tag_list = params[:post][:post_tag_name].split(nil)
      if @post.save
        @post.save_tag(@tag_list)
        redirect_back(fallback_location: root_path)
      else
        redirect_back(fallback_location: root_path)
      end
  end

  def edit
    @post = current_user.posts.find(params[:id])
    @tag_list = @post.post_tags.pluck(:post_tag_name).join(',')
  end

  def update
    @post = current_user.posts.find(params[:id])
    @tag_list = params[:post][:post_tag_name].split(',')
    if @post.update(post_params)
      @post.save_tag(@tag_list)
      # redirect_back(fallback_location: root_path)
      redirect_to post_path
    else
      redirect_back(fallback_location: root_path)
    end
  end

  private
  def post_params
    # params.require(:post).permit(:title, :description, :content)
    params.require(:post).permit(:content, { post_tag_ids: [] })
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end

  def edit
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | CommentFunction
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    .notice
      = notice
    .alert
      = alert
    = yield

app/views/posts/edit.html.slim
h3 編集する
= form_with model: @post do |f|
  div
    p= f.text_field :title, placeholder: 'タイトル'
    p= f.text_area :description, placeholder: 'あらすじ'
    p= f.text_area :content, placeholder: '本文'
    p= f.text_field :post_tag_name, value: @tag_list, placeholder: 'タグ'
    p= f.submit

app/views/posts/index.html.slim
/ - if user_signed_in?
/   = link_to 'マイページへ', user_path(current_user.id)
/   = link_to 'ログアウト', destroy_user_session_path, method: :delete
/ - else
/   = link_to 'ユーザー登録', new_user_registration_path
/   = link_to 'ログイン', new_user_session_path

br

h3 タグリスト

- @tag_list.each do |list|
  span
    = link_to list.post_tag_name, post_tag_posts_path(post_tag_id: list.id)
    = "(#{list.posts.count})"

br
hr
br

h3 投稿する
= form_with(model: @post, url: posts_path, local: true) do |f|
  / = f.text_field :title, placeholder: 'タイトル'
  / br
  / = f.text_area :description, placeholder: 'あらすじ'
  / br
  = f.text_area :content, placeholder: '本文', class: 'post-text'
  br
  br
  = "スペースを入力することで複数のタグを付けることができます。"
  br
  = "例：音楽 文芸 スポーツ"
  br
  = f.text_field :post_tag_name, placeholder: '投稿にタグ付けする', class: 'tag-text'
  br
  / = "【タグを選択できます】"
  / = f.collection_check_boxes :post_tag_ids, @tag_list, :id, :post_tag_name, include_hidden: false do |tag|
  /   = tag.check_box
  /   = tag.text
  br
  br
  = f.submit

br
hr
br

h3 投稿一覧
- @posts.each do |post|
  p
    / = link_to post.user.email, post.user
    / br
    = link_to post.content, post

app/views/posts/search.html.slim
h2 投稿一覧
hr
h3 タグリスト

- @tag_list.each do |list|
  span
    = link_to list.post_tag_name, post_tag_posts_path(post_tag_id: list.id)
    = "(#{list.posts.count})"
hr
br
br
= "タグが ─ "
strong
  = "#{@tag.post_tag_name}"
= " ─ の投稿一覧"
br
- @posts.each do |post|
  p
    / = link_to post.user.email, post.user
    / br
    = link_to post.content, post
br
= link_to 'ホーム', root_path

app/views/posts/show.html.slim
h1 投稿詳細

div
  / p= @post.user.email
  / p= @post.title
  / p= "投稿内容が入ります。"
  / p= @post.description
  p= @post.content
  / p= link_to '編集', edit_post_path(@post)


= "タグ: "
- @post_tags.each do |tag|
  span
    = link_to tag.post_tag_name, post_tag_posts_path(post_tag_id: tag.id)
    = "(#{tag.posts.count})"
/ = form_with(model:[@post, @comment], method: :post) do |f|
/     = f.text_area :content
/     = f.hidden_field :post_id, value: @post.id
/     = f.submit 'コメントする'
/
/ h2 コメント一覧
/
/ - @comments.each do |comment|
/   p
/     = link_to comment.user.email, comment.user
/
/     = comment.content
br
br
= link_to 'ホーム', root_path

app/views/users/edit.html.slim
h1 Users#edit
p Find me in app/views/users/edit.html.slim

app/views/users/show.html.slim
h1 ユーザー詳細ページ

h3
  = @user.email

h3 投稿内容
- @user.posts.each do |post|
  = link_to post.content, post

hr

= link_to 'ホーム', root_path